//! Parity test: every block of every fixture in zkvm/fixtures/*.json must
//! reproduce the ethereumjs engine's post state root, gas used and raw tx
//! commitment byte-for-byte.
//!
//! Fixtures are generated by `pnpm exec tsx scripts/gen-stf-fixtures.ts` at
//! the repo root (they self-verify against the engine when generated).

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use alloy_primitives::{Address, Bytes, B256, U256};
use serde::Deserialize;
use stf_core::{execute_block_full, StateMap};
use stf_types::{AccountState, BlockEnvV1, StfInput};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    scenario: String,
    room_id: String,
    chain_id: u64,
    hardfork: String,
    blocks: Vec<FixtureBlock>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureBlock {
    block_number: u64,
    env: FixtureEnv,
    pre_state: Vec<FixtureAccount>,
    raw_txs: Vec<Bytes>,
    prev_state_root: B256,
    expected_post_root: B256,
    expected_gas_used: u64,
    expected_tx_commitment: B256,
    post_state: Vec<FixtureAccount>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureEnv {
    number: u64,
    timestamp: u64,
    gas_limit: u64,
    coinbase: Address,
    base_fee: String,
    prev_randao: B256,
    difficulty: String,
    excess_blob_gas: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureAccount {
    address: Address,
    nonce: String,
    balance: String,
    #[serde(default)]
    code: Option<Bytes>,
    #[serde(default)]
    storage: BTreeMap<B256, B256>,
}

fn hex_u64(s: &str) -> u64 {
    u64::from_str_radix(s.trim_start_matches("0x"), 16).expect("hex u64")
}

fn hex_u256(s: &str) -> U256 {
    U256::from_str_radix(s.trim_start_matches("0x"), 16).expect("hex u256")
}

fn to_account_state(a: &FixtureAccount) -> (Address, AccountState) {
    (
        a.address,
        AccountState {
            nonce: hex_u64(&a.nonce),
            balance: hex_u256(&a.balance),
            code: a.code.clone().unwrap_or_default(),
            storage: a
                .storage
                .iter()
                .map(|(k, v)| (U256::from_be_bytes(k.0), U256::from_be_bytes(v.0)))
                .collect(),
        },
    )
}

/// Human-readable diff of computed post-state vs the engine's dump.
fn diff_states(computed: &StateMap, expected: &[FixtureAccount]) -> String {
    let mut out = String::new();
    let expected_map: BTreeMap<Address, &FixtureAccount> =
        expected.iter().map(|a| (a.address, a)).collect();

    for (addr, rec) in &computed.accounts {
        match expected_map.get(addr) {
            None => out.push_str(&format!("  + rust-only account {addr}\n")),
            Some(exp) => {
                if rec.nonce != hex_u64(&exp.nonce) {
                    out.push_str(&format!(
                        "  ~ {addr} nonce rust={} engine={}\n",
                        rec.nonce,
                        hex_u64(&exp.nonce)
                    ));
                }
                if rec.balance != hex_u256(&exp.balance) {
                    out.push_str(&format!(
                        "  ~ {addr} balance rust={} engine={}\n",
                        rec.balance,
                        hex_u256(&exp.balance)
                    ));
                }
                let exp_code = exp.code.clone().unwrap_or_default();
                if rec.code != exp_code {
                    out.push_str(&format!("  ~ {addr} code differs\n"));
                }
                let exp_storage: BTreeMap<U256, U256> = exp
                    .storage
                    .iter()
                    .map(|(k, v)| (U256::from_be_bytes(k.0), U256::from_be_bytes(v.0)))
                    .collect();
                for (k, v) in &rec.storage {
                    match exp_storage.get(k) {
                        None => out.push_str(&format!("  + {addr} rust-only slot {k:#x}={v:#x}\n")),
                        Some(ev) if ev != v => out.push_str(&format!(
                            "  ~ {addr} slot {k:#x} rust={v:#x} engine={ev:#x}\n"
                        )),
                        _ => {}
                    }
                }
                for (k, v) in &exp_storage {
                    if !rec.storage.contains_key(k) {
                        out.push_str(&format!("  - {addr} engine-only slot {k:#x}={v:#x}\n"));
                    }
                }
            }
        }
    }
    for addr in expected_map.keys() {
        if !computed.accounts.contains_key(addr) {
            out.push_str(&format!("  - engine-only account {addr}\n"));
        }
    }
    if out.is_empty() {
        out.push_str("  (no per-account differences — trie encoding mismatch?)\n");
    }
    out
}

#[test]
fn parity_all_fixtures() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("fixtures");
    let mut entries: Vec<_> = fs::read_dir(&dir)
        .unwrap_or_else(|e| {
            panic!(
                "cannot read {dir:?}: {e} — generate fixtures first: pnpm exec tsx scripts/gen-stf-fixtures.ts"
            )
        })
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .filter(|p| {
            !p.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("receipt-"))
        })
        .collect();
    entries.sort();
    assert!(!entries.is_empty(), "no fixtures in {dir:?}");

    let mut blocks_run = 0usize;
    let mut failures = Vec::new();

    for path in &entries {
        let fx: Fixture = serde_json::from_str(&fs::read_to_string(path).unwrap())
            .unwrap_or_else(|e| panic!("bad fixture {path:?}: {e}"));
        // Newly generated v4 evidence is pinned to Osaka. The pre-v4
        // fixtures retain their historical Cancun label and cover only the
        // opcode/transaction subset whose result is unchanged under Osaka.
        assert!(
            matches!(fx.hardfork.as_str(), "osaka" | "cancun"),
            "{}: unexpected hardfork {}",
            fx.scenario,
            fx.hardfork
        );
        let room_id: u64 = fx.room_id.parse().expect("roomId");

        for block in &fx.blocks {
            let input = StfInput {
                room_id,
                block_number: block.block_number,
                prev_state_root: block.prev_state_root,
                state: block.pre_state.iter().map(to_account_state).collect(),
                raw_txs: block.raw_txs.clone(),
                env: BlockEnvV1 {
                    number: block.env.number,
                    timestamp: block.env.timestamp,
                    gas_limit: block.env.gas_limit,
                    coinbase: block.env.coinbase,
                    base_fee: hex_u256(&block.env.base_fee),
                    prev_randao: block.env.prev_randao,
                    difficulty: hex_u256(&block.env.difficulty),
                    excess_blob_gas: hex_u64(&block.env.excess_blob_gas),
                    chain_id: fx.chain_id,
                },
                block_hashes: Vec::new(),
            };

            let label = format!("{} block {}", fx.scenario, block.block_number);
            let outcome = match execute_block_full(&input) {
                Ok(o) => o,
                Err(e) => {
                    failures.push(format!("{label}: STF error: {e}"));
                    continue;
                }
            };
            blocks_run += 1;

            if outcome.journal.post_state_root != block.expected_post_root {
                failures.push(format!(
                    "{label}: POST ROOT mismatch\n  rust   {}\n  engine {}\n{}",
                    outcome.journal.post_state_root,
                    block.expected_post_root,
                    diff_states(&outcome.post_state, &block.post_state)
                ));
            }
            if outcome.journal.tx_commitment != block.expected_tx_commitment {
                failures.push(format!(
                    "{label}: TX COMMITMENT mismatch rust {} engine {}",
                    outcome.journal.tx_commitment, block.expected_tx_commitment
                ));
            }
            if outcome.gas_used != block.expected_gas_used {
                failures.push(format!(
                    "{label}: GAS USED mismatch rust {} engine {}",
                    outcome.gas_used, block.expected_gas_used
                ));
            }
            assert_eq!(outcome.journal.prev_state_root, block.prev_state_root);
            assert_eq!(outcome.journal.v, stf_types::JOURNAL_VERSION);
            assert_eq!(outcome.journal.room_id, room_id);
            assert_eq!(outcome.journal.block_number, block.block_number);
            // journal v2: the committed env hash must be the hash of the env
            // that was actually executed, not a placeholder.
            assert_eq!(
                outcome.journal.env_hash,
                stf_types::block_env_hash(&input.env),
                "{label}: journal env_hash does not commit the executed environment"
            );
        }
    }

    assert!(
        failures.is_empty(),
        "STF parity failures ({} of {} blocks):\n{}",
        failures.len(),
        blocks_run,
        failures.join("\n")
    );
    println!(
        "parity OK: {blocks_run} blocks across {} fixtures",
        entries.len()
    );
    assert!(
        blocks_run >= 15,
        "expected at least 15 blocks, ran {blocks_run}"
    );
}
